c_compiler_version:            # [osx]
  - 17                         # [osx]
cxx_compiler_version:          # [osx]
  - 17                         # [osx]

channel_targets:
  - conda-forge llvm_rc

channel_sources:
  - conda-forge/label/llvm_rc,conda-forge
